name: Deploy to Kubernetes
description: Deploy to Kubernetes
inputs:
  image:
    description: Image to deploy
    required: true
  embed-title:
    description: Title of the embed
    required: true
  kube_config:
    description: base64 encoded kube config
    required: true
  webhook-url:
    description: Discord Webhook URL
    required: true
  service:
    description: Name of the service
    required: true
runs:
  using: composite
  steps:
    - name: Send Discord Webhook
      if: ${{ inputs.embed-title != '' }}
      uses: ./.github/actions/discord-webhook
      with:
        webhook-url: ${{ inputs.webhook-url }}
        embed-color: 15105570
        embed-title: "${{ inputs.embed-title }}"
        embed-description: "```Deploy Started```"

    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.5.4"

    - name: Set image
      working-directory: ./k8s
      shell: bash
      run: |
        kustomize edit set image replaceme=${{ inputs.image }}
        kustomize build . > ./ci-deployment.yaml

    - name: Deploy image to k8s cluster
      uses: bbedward/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube_config }}
      with:
        args: apply -f ./k8s/ci-deployment.yaml

    - name: Send Discord Webhook
      if: ${{ failure() && inputs.embed-title != '' }}
      uses: ./.github/actions/discord-webhook
      with:
        webhook-url: ${{ inputs.webhook-url }}
        embed-title: "${{ inputs.embed-title }}"
        embed-color: 15548997
        embed-description: "```🚨 Deploy Failed 🚨```"
